### ISSUE TITLE
[Enhancement]Remove redundant expression

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#124]
we need to remove redundant expression.

- [ ] MysqlResult.RELEASE
- [ ] MySqlResult.SUM
- [ ] PreparedExecuteMessage.DISPOSE
- [ ] e.t.c.

**Comment by JohnNiang** [comment]
Hi @jchrys , I'm willing to contribute this issue.

But I would like to know the reason why we remove those expressions. IMO, these variables are the same as lambda expression. I'm looking forward to your reply.

**Comment by jchrys** [comment]
Thank you for your comment and willingness to contribute. 
Regarding the issue of removing it, I believed that caching the lambda wouldn't serve a significant purpose and wouldn't necessarily enhance the code's readability.

```Java
            return OperatorUtils.discardOnCancel(Flux.fromIterable(buffers))
                .doOnDiscard(ByteBuf.class, RELEASE) // Should lookup RELEASE and RELEASE is used on only one place. :(
                .map(this::consume);
```

```Java
            return OperatorUtils.discardOnCancel(Flux.fromIterable(buffers))
                .doOnDiscard(ByteBuf.class, ByteBuf::release) // no need to lookup if you're familiar with Netty.
                .map(this::consume);
```
