### ISSUE TITLE
Improved Decoder Selection

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#153]
**Is your feature request related to a problem? Please describe.**
We currently find an appropriate decoder iteratively, which is slow and inefficient. This process could be significantly optimized.

**Describe the solution you'd like**
Implementing a fast path for decoder selection using map. This would streamline the decoder selection process, leading to improved performance and efficiency.

**Comment by mirromutth** [comment]
We can make a fast path for default types, just like [`mariadb-connector-r2dbc` does](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/76f058b7fec4e9bfadce36d4da56d4f8b86ce848/src/main/java/org/mariadb/r2dbc/util/MariadbType.java).
