### ISSUE TITLE
[QUESTION] sql timeout option

### ISSUE THREAD

**Issue by kihwankim** [asyncer-io/r2dbc-mysql#160]
## Summary

I would like to find query timeout property option

## Detailed description

I try to find query time out options but I can not find....
is there the same on as the jpa setting information blow??

```
spring.jpa.properties.javax.persistence.query.timeout=5000
spring.jpa.properties.javax.persistence.lock.timeout=5000
```

## Relevant context

- JPA properties which I would like to find
```
spring.jpa.properties.javax.persistence.query.timeout=5000
spring.jpa.properties.javax.persistence.lock.timeout=5000
```

## Your environment

- spring boot: 2.6
- spring data r2dbc
- dev.miku r2dbc-mysql: 0.8.2.RELEASE

## Checklist
- [x] I have searched the existing issues to make sure my question has not been asked before
- [x] I have provided all the necessary information and context to help answer my question
- [x] I have read the documentation and/or README for this project (if applicable)

**Comment by jchrys** [comment]
Hi, We do not support query timeout option.
but I think you can utilize your reactive library to apply the timeout.
Thanks!
