### ISSUE TITLE
Aligning `Connection#setTransactionIsolationLevel` Behavior with `r2dbc-spi` Specification

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#192]
# Issue

The current implementation of `Connection#setTransactionIsolationLevel` does not align with its specification. According to the specification(), this method should configure the isolation level for the connection, and the specified isolation level should apply to all subsequent transactions. However, the current behavior applies the isolation level only to the next transaction.

# Proposal
Aligning the behavior of `Connection#setTransactionIsolationLevel` with its specification. The implementation should be adjusted so that the configured isolation level persists for all subsequent transactions until explicitly changed.

# Action Items
- Modify the implementation of `Connection#setTransactionIsolationLevel` to align with the specification.(`AbstractTransactionState` could be utilized if needed )
- Verify and update the transaction isolation behavior in the entire project to ensure consistency and adherence to the proposed changes.

## Refs
- r2dbc-spi specification: https://github.com/r2dbc/r2dbc-spi/blob/160cd2743f8ce8551618abcd96fa1d7ee37f8f38/r2dbc-spi/src/main/java/io/r2dbc/spi/Connection.java#L221C12-L221C12
- mysql-dev doc: https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html#set-transaction-scope

**Comment by JohnNiang** [comment]
I'm willing to contribute this enhancement.

/assign

**Comment by jchrys** [comment]
> I'm willing to contribute this enhancement.
> 
> /assign

Thanks!

**Comment by jchrys** [comment]
#202 resolved this issue
