### ISSUE TITLE
Check and remove MariaDB 10.x fake prefix in version

### ISSUE THREAD

**Issue by mirromutth** [asyncer-io/r2dbc-mysql#203]
MariaDB 10.x has a replication hack that sends a prefixed version `5.5.5-` in the handshake. e.g. `5.5.5-10.6.6-MariaDB`

Check the replication hack and remove fake prefix in `ServerVersion#parse`.

Consider adding a boolean property to `ServerVersion` to check if the server is MariaDB instead of just checking via capabilities.

See also [`r2dbc-mariadb` does](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/4f9385fd9cabcab4557c1f228cfdafa4a3a27ce2/src/main/java/org/mariadb/r2dbc/message/server/InitialHandshakePacket.java#L107)

**Comment by jchrys** [comment]
for future ref
- https://jira.mariadb.org/browse/MDEV-4088
