### ISSUE TITLE
[feature]Enable Leak detection in CI pipeline

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#241]
**Is your feature request related to a problem?**
We lack mechanisms for detecting ByteBuffer memory leaks during development, might leading to potential issues in production.

**Describe the solution you'd like**
Enable leak detection feature during testing phases, ensuring leak reports are integrated into our CI pipeline for immediate action.

**Additional context**

**Comment by mirromutth** [comment]
Maybe we can add `-Dio.netty.leakDetection.level=PARANOID` to GitHub Actions for detecting leak.

**Comment by jchrys** [comment]
Sure! Let me work on it :D
