### ISSUE TITLE
[bug] Deploy broken

### ISSUE THREAD

**Issue by mirromutth** [asyncer-io/r2dbc-mysql#246]
**Describe the bug**

1. Unexpected tag formatting `r2dbc-mysql-parent-${version}`
2. Missing publish of `r2dbc-mysql-parent`

Import `1.1.2-SNAPSHOT`, Gradle reports:

```log
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve io.asyncer:r2dbc-mysql:1.1.2-SNAPSHOT.
     Required by:
         project :
      > Could not resolve io.asyncer:r2dbc-mysql:1.1.2-SNAPSHOT.
         > Could not parse POM https://s01.oss.sonatype.org/content/repositories/snapshots/io/asyncer/r2dbc-mysql/1.1.2-SNAPSHOT/r2dbc-mysql-1.1.2-20240222.165350-14.pom
            > Could not find io.asyncer:r2dbc-mysql-parent:1.1.2-SNAPSHOT.
```

**To Reproduce**

1. Run `RELEASE` action.
2. Import repository `r2dbc-mysql:1.1.2-SNPAHOT`

**Expected behavior**

1. Tag should be `r2dbc-mysql-${version}` or `v${version}`. Use `maven-release-plugin` configuration fixes it
2. Add `r2dbc-mysql-parent` deploying in action workflow

**Additional context**

It should be caused by #239

**Comment by mirromutth** [comment]
@jchrys I'll force push to undo bot commits and remove the unexpected tag.

**Comment by jchrys** [comment]
> **Describe the bug**
> 
> 
> 
> 1. Unexpected tag formatting `r2dbc-mysql-parent-${version}`
> 
> 2. Missing publish of `r2dbc-mysql-parent`
> 
> 
> 
> Import `1.1.2-SNAPSHOT`, Gradle reports:
> 
> 
> 
> ```log
> 
> Execution failed for task ':compileJava'.
> 
> > Could not resolve all files for configuration ':compileClasspath'.
> 
>    > Could not resolve io.asyncer:r2dbc-mysql:1.1.2-SNAPSHOT.
> 
>      Required by:
> 
>          project :
> 
>       > Could not resolve io.asyncer:r2dbc-mysql:1.1.2-SNAPSHOT.
> 
>          > Could not parse POM https://s01.oss.sonatype.org/content/repositories/snapshots/io/asyncer/r2dbc-mysql/1.1.2-SNAPSHOT/r2dbc-mysql-1.1.2-20240222.165350-14.pom
> 
>             > Could not find io.asyncer:r2dbc-mysql-parent:1.1.2-SNAPSHOT.
> 
> ```
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 
> 
> 1. Run `RELEASE` action.
> 
> 2. Import repository `r2dbc-mysql:1.1.2-SNPAHOT`
> 
> 
> 
> **Expected behavior**
> 
> 
> 
> 1. Tag should be `r2dbc-mysql-${version}` or `v${version}`. Use `maven-release-plugin` configuration fixes it
> 
> 2. Add `r2dbc-mysql-parent` deploying in action workflow
> 
> 
> 
> **Additional context**
> 
> 
> 
> It should be caused by #239 
> 
> 

Thanks!

(I guess we might need to remove parent dependency from r2dbc-mysql module xml. By doing that I think we could prevent the parent artifact from being deployed as a r2dbc-mysql's dependency)

**Comment by mirromutth** [comment]
Yep, you are right. At least for now, we do not need a parent module unless we are going to implement `r2dbc-mysql-extension-jackson` or something else.
