### ISSUE TITLE
[Release]v1.1.3 

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#269]
All the items in 1.1.3 milestones are closed. [link](https://github.com/asyncer-io/r2dbc-mysql/milestone/17?closed=1)
I think now is good time to release 1.1.3 WDYT? @mirromutth

**Comment by mirromutth** [comment]
Yes, we can release it after last check

**Comment by jchrys** [comment]
got it :D

**Comment by jchrys** [comment]
https://github.com/asyncer-io/r2dbc-mysql/releases/tag/r2dbc-mysql-1.1.3
