### ISSUE TITLE
Need to Update GH actions

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#27]
We used to maintain 'trunk' branch.

but we need to support '0.9' branch as well for bugfixes and minor feature updates.

so we need to update gh actions yml files to support both 'trunk' and '0.9' branches.

**Comment by JohnNiang** [comment]
IMO, the issue has been fixed by https://github.com/asyncer-io/r2dbc-mysql/pull/102 and <https://github.com/asyncer-io/r2dbc-mysql/pull/103>.

Can we close this issue : P

**Comment by jchrys** [comment]
Thanks!
