### ISSUE TITLE
[feature] return a scalar value instead of a buffer for bit fields, such as Byte.

### ISSUE THREAD

**Issue by underbell** [asyncer-io/r2dbc-mysql#277]
**Is your feature request related to a problem? Please describe.**
r2dbc has ConverterNotFoundException [java.nio.HeapByteBuffer] to type [java.lang.Boolean] on boot 3.3.0
https://github.com/spring-projects/spring-data-relational/issues/1824

**Describe the solution you'd like**
return a scalar value instead of a buffer for bit fields, such as Byte.

**Additional context**
https://github.com/spring-projects/spring-data-relational/issues/1824#issuecomment-2185738223

**Comment by jchrys** [comment]
@underbell
Thanks for reporting :D

**Comment by jchrys** [comment]
BIT(1) is should  be represented as `java.lang.Boolean` just like mysql connector-j's implementation.

**Comment by jchrys** [comment]
ref https://docs.oracle.com/cd/E17952_01/connector-j-en/connector-j-reference-type-conversions.html
