### ISSUE TITLE
connection leak when using r2dbc-pool with r2dbc-mysql

### ISSUE THREAD

**Issue by 1528110566** [asyncer-io/r2dbc-mysql#294]
**Environment**
Windows 11
JDK 1.8.0-381
Spring-parent 2.7.13
r2dbc-mysql 0.9.3

**Describe the bug**
I've been stucked with an bug recently, and I search anywhere on GitHub but nothing.
Here is an issue that very close to answer. https://github.com/pgjdbc/r2dbc-postgresql/issues/661
So I wrote an issue under this repo.

It's quit simple. Update something in `database transaction`, throw an exception if the updated rows is not 1(always true because it's not exists). 2 update statements are triggled by `Flux` parallel.

``` java
Query query = Query.query(Criteria.where("id").is(3));
Update update = Update.update("name", "3");
List<Integer> list = new ArrayList<>();
list.add(0);
list.add(1);
for (int i = 0; i < 1000; i++) {
    Flux.fromIterable(list)
            .flatMap(item -> {
                return transactionalOperator.transactional(template.update(query, update, User.class)
                        .doOnNext(res -> {
                            if (res != 1) {
                                throw new RuntimeException("test");
                            }
                        }));
            })
            .subscribe();
}
```

The funny thing is,  when I change `.doOnNext` to another block(attention on `)`), it's works as expected.
``` java
Query query = Query.query(Criteria.where("id").is(3));
Update update = Update.update("name", "3");
List<Integer> list = new ArrayList<>();
list.add(0);
list.add(1);
for (int i = 0; i < 1000; i++) {
    Flux.fromIterable(list)
            .flatMap(item -> {
                return transactionalOperator.transactional(template.update(query, update, User.class))
                        .doOnNext(res -> {
                            if (res != 1) {
                                throw new RuntimeException("test");
                            }
                        });
            })
            .subscribe();
}
```

So, I believe something must not compatible with `cancel in reactor` and `spring-tx`.
Another thing confusing me is, why the number of `r2dbc_pool_acquired_connections` always `9`.

![image](https://github.com/user-attachments/assets/d99c9c56-ff5e-4217-a5f3-07e5506db6a8)
![image](https://github.com/user-attachments/assets/1af4cbea-141a-4166-a5c8-fc35231d2cdc)

**To Reproduce**
https://github.com/1528110566/r2dbc-connection-leak-demo
This is a demo that can reproduce this bug. 
1. call http://localhost:8080/test
2. wait background threads are finished
3. call http://localhost:8080/actuator/prometheus
4. search `r2dbc_pool_acquired_connections`and `r2dbc_pool_idle_connections`. We'll find the number of connection in the pool is not as expected. This can be proved with debugging on https://github.com/r2dbc/r2dbc-pool/blob/bf6540eee26aa55bba4cb6ab0c6a3c622524679c/src/main/java/io/r2dbc/pool/ConnectionPool.java#L106. We'will find the number of connection is actually smaller than expected.

**Comment by jchrys** [comment]
Thanks for describing the issue in detail. Let me look into it

**Comment by jchrys** [comment]
@1528110566 
This doesn't seem to be caused by r2dbc-mysql. Could you kindly raise a ticket with [r2dbc-pool](https://github.com/r2dbc/r2dbc-pool)?

**Comment by 1528110566** [comment]
Sure, I will.

**Comment by 1528110566** [comment]
Expecting a good news...
https://github.com/r2dbc/r2dbc-pool/issues/219
