### ISSUE TITLE
Create Issue template

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#60]
This repository is lack of issue template..

**Comment by Soumya-Kushwaha** [comment]
I'd like to work on this as per https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

If there are any other suggestions, kindly let me know and assign the issue.

**Comment by jchrys** [comment]
Hello, @Soumya-Kushwaha.
Great to hear that you would like to work on this issue. As of now, I don't have any other suggestions. 
Thanks for your contribution!
