### ISSUE TITLE
[feature] Start a plan for Support MariaDB

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#72]
**Is your feature request related to a problem? Please describe.**
Currently, the r2dbc-mysql project does not support MariaDB, which limits its usability for users who are using MariaDB as their preferred database. Although MariaDB and MySQL share a similar protocol, the existing r2dbc-mysql implementation does not have the necessary logic to handle the differences between the two database systems. Therefore, I would like to request the addition of support for MariaDB in the r2dbc-mysql project.

**Describe the solution you'd like**
I would like to propose adding support for MariaDB in the r2dbc-mysql project. Since MariaDB and MySQL share a similar protocol, it should be possible to extend the existing implementation to accommodate MariaDB with some additional logic. This would involve introducing branching in the code to handle specific behaviors or features that are unique to MariaDB.

**Additional context**
Supporting MariaDB in the r2dbc-mysql project would provide users with more options and flexibility when choosing their preferred database. It would leverage the similarities between MariaDB and MySQL, making it possible to reuse much of the existing codebase. However, it is important to carefully address any differences between the two database systems to ensure correct behavior.

Adding integration tests is crucial to guarantee that the implementation works as expected with MariaDB. These tests should cover various scenarios and edge cases to validate the compatibility and functionality of r2dbc-mysql with MariaDB.

I believe that by implementing this feature, the r2dbc-mysql project will become a more comprehensive and inclusive solution for developers working with both MySQL and MariaDB databases.

**Comment by mirromutth** [comment]
According to my personal opinion, this feature may need to be split into multiple sub-features for implementation, and it is likely to be a fairly long-term effort.

AFAIK, some differences between MySQL and MariaDB that should make for feature tickets:

1. Capabilities: MariaDB contains more flags in the last 4 bytes of the 10 bytes filter (the reserved field) of `HandshakeV10Request`, which expands capabilities to 64 bits. The `CLIENT_MYSQL=1` flag is used to indicate whether to use the MySQL compatible protocol. MariaDB 10.2 and above will unset this flag. If this flag is unset, the server is assumed to be MariaDB. Note that in the MySQL server, this flag is called `LONG_PASSWORD`, and it is not currently used by `r2dbc-mysql`. We can consider reinterpreting it for support MariaDB. See also https://mariadb.com/kb/en/connection/#capabilities
2. `RETURNING`: MariaDB support to use `INSERT ... RETURNING col1[, col2[, col3...]]` for returns a result-set of the inserted rows. The response looks like the execution result of a `SELECT` statement, and the last `OkMessage` will get the updated rows. See also https://mariadb.com/kb/en/insertreturning/
3. Column metadata: MariaDB use `MYSQL_TYPE_STRING` for JSON, and MySQL use `MYSQL_TYPE_JSON`. See also https://mariadb.com/kb/en/result-set-packets/#field-types
4. Password plugins: e.g. `client_ed25519`, `dialog`, `auth_gssapi_client`. See also https://mariadb.com/kb/en/connection/
5. Skip metadata: not like MySQL optional metadata, MariaDB will send metadata in prepare statement first fetch 🤔 (not sure, need investigation). See also `MARIADB_CLIENT_CACHE_METADATA` in capabilities

I've only tried using MariaDB a few times, so probably quite unprofessional, this list needs to be supplemented by more experts.

**Comment by mirromutth** [comment]
We will follow the entire issue as a public project: https://github.com/orgs/asyncer-io/projects/3
