### ISSUE TITLE
[feature] Java LTS versions compatibility tests

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#77]
**Is your feature request related to a problem? Please describe.**
We're lack of java LTS versions compatibility tests

**Describe the solution you'd like**
Adding compatibility test using github actions.

**Additional context**

**Comment by saurabhyadavdev** [comment]
Hey, I would like to contribute. What should the compatibility tests do?

**Comment by jchrys** [comment]
Hello, @saurabhyadav1985.
Thank you for your interest in contributing! 
Currently, our Github action only builds and runs unit tests against JDK8, as you can see in the ./github/workflows/unit-tests.yml file. 
However, we are planning to create additional Github actions to build and run tests against JDK LTS versions >= 8. 
We appreciate any help you can offer in this effort!

**Comment by saurabhyadavdev** [comment]
Thanks, so we need two more jobs in workflow for Java 11 and 17?

**Comment by jchrys** [comment]
Yes, that's correct.

**Comment by saurabhyadavdev** [comment]
I added jobs for java 11 & 17. https://github.com/jchrys/r2dbc-mysql/pull/1

However I am unable to run these using github actions. I have rasied PR still no sure whether job ran. How can I run it manually?

**Comment by jchrys** [comment]
Once you create a PR to this repository(`asyncer-io/r2dbc-mysql`), I can make it run.

**Comment by saurabhyadav1985** [comment]
Created PR https://github.com/asyncer-io/r2dbc-mysql/pull/80

**Comment by jchrys** [comment]
resolved by #80
