### ISSUE TITLE
[feature] Simplify build jobs using a matrix

### ISSUE THREAD

**Issue by jchrys** [asyncer-io/r2dbc-mysql#83]
## Is your feature request related to a problem? Please describe.
The current build&unit test jobs(./github/workflows/unit-tests.yml) in the GitHub Actions workflow have significant duplication, with the only difference being the java-version used. This makes the workflow harder to maintain and update when changes are required.

## Describe the solution you'd like
I suggest using a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) to reduce duplication in the GitHub Actions workflow. By utilizing a matrix, we can define a single build job that iterates over the different java-version values, making the workflow more concise and easier to maintain.

## Additional context
reported by #80

**Comment by saurabhyadavdev** [comment]
Raised PR, please have a look.
