### ISSUE TITLE
get nothing if there is @Data annotation on the entity class

### ISSUE THREAD

**Issue by victor-yi** [asyncer-io/r2dbc-mysql#90]
**Describe the bug**

- If an entity class has annotation `@Data` from lombok library, we get nothing from database. 
- It still not works when we put `@NoArgsConstructor` on the entity class. 
- If we remove all annotations from lombok library and generate all getter and setter, it works.

I'm not sure if it's an issue here or should we report it to spring r2dbc, just create an issue here for tracking.

**To Reproduce**
db schema:

```sql
create table user (
    id bigint auto_increment primary key ,
    name varchar(20) not null ,
    age tinyint not null
) engine = InnoDB;
```

entity class:

```java
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

@Data
@Table("user")
public class User {
    @Id
    private Long id;
    private String name;
    private Integer age;
}

```

**Comment by jchrys** [comment]
Hello, @victor-yi.

Thank you for reaching out and providing the details of the issue you are encountering. 
While I understand your concerns, it would be more appropriate to report this issue to the Spring Data Relational team, as it does not seem to be directly related to the r2dbc-mysql project.

Please feel free to reach out if you have any other questions or concerns related to the r2dbc-mysql project.

Thanks!
